### PR TITLE
Add due date to Todo

### PR DESCRIPTION
**Pull request by hnq90**

### CODE REVIEW

**Comment by kenji4569** [comment]
- "isObjectEqual" using "deepEqual" remains, which is not necessary under immutable redux reducers.
- "callback" prop of DateWidget is never used, I think it should be renamed to "setSelectedDate", and further it would be better to rename from ""setSelectedDate" to just "onChange", and "inputValue" to just "value".

**Comment by hnq90** [comment]
@kenji4569 Thank you,

> "isObjectEqual" using "deepEqual" remains, which is not necessary under immutable redux reducers.

Actually, I have to use deep check because after I selected due_date, I send the callback to parent component (TodoForm) to setState of due_date to selected day. But I got maximum call stack error because of loop rendering when state change. (shouldComponentUpdate is always true event the attribute of it are different).
Do you have any idea?

> "callback" prop of DateWidget is never used, I think it should be renamed to "setSelectedDate", and further it would be better to rename from ""setSelectedDate" to just "onChange", and "inputValue" to just "value".

Yes, I declared "callback" but I changed it to setSelectedDate and forgot to rename it.
I think onChange is not preferable because It may be conflict with browser event (onchange). I've tested and it trigger that function everytime I click on DateWidget.

**Comment by kenji4569** [comment]
> I got maximum call stack error 

The core issue of the error might not be related to shouldComponentUpdate, since by default this function is not defined but the component should work. Please inspect further.

> I think onChange is not preferable because It may be conflict with browser event (onchange).

The better spec would be as in https://github.com/Hacker0x01/react-datepicker using "selected" and "onChange". I think conflict would not occur or avoidable.

And you should not put input hidden due_date tag on TodoForm directly, instead put it in DateWidget.

**Comment by kenji4569** [comment]
Sorry forget abount "And you should not put input hidden due_date tag on TodoForm directly, instead put it in DateWidget.". I rethink that it would be better to separate them

**Comment by hnq90** [comment]
@kenji4569 

> The core issue of the error might not be related to shouldComponentUpdate, since by default this function is not defined but the component should work. Please inspect further.

Here my screenshot for that infinite loop error:
**RangeError**
selection_012 

**Log nextState and this.state to console**
selection_013

As you can see, in the first time, `this.state.due_date` is blank. So `shouldComponentUpdate` is triggered.
But after `setState` of `due_date`, the infinite loop occurred.

This is your old code:

```
shouldComponentUpdate(nextProps, nextState) {
    console.log(nextState, this.state)
    return (
      nextProps.todo !== this.props.todo ||
      nextState !== this.state
      // !isObjectEqual(nextProps.todo, this.props.todo) ||
      // !isObjectEqual(nextState, this.state)
    );
  }
```

**Comment by kenji4569** [comment]
I got it. You should not call "setSelectedDate" on first initialization of DateWidget. "onChange" event of an hidden input tag will do this. And why did you put such a hidden input tag inside DateWidget, when another hidden input tag is present outside DateWidget?

**Comment by kenji4569** [comment]
Or, alternatively, put the identity check inside _setSelectedDate method.

**Comment by kenji4569** [comment]
As in https://github.com/Hacker0x01/react-datepicker, the former approach would be better.

**Pull request merged**
